### ISSUE TITLE
Error in first line of org-project.el

### ISSUE THREAD

**Issue by doolio** [Fuco1/.emacs.d#16]
The first line of org-projects.el is as follows:

```
;;; org-package.el --- Additional code for managing packages
```

but I think you meant

```
;;; org-project.el --- Additional code for managing projects
```

I like probably so many many others have been configuring a GTD system within org based heavily on Bernt Hansen's great article at http://doc.norang.ca/org-mode.html but then I discovered your configuration and this file and I like how you refactored (is that the correct term? - I'm slowly trying to learn how to programme) many of his functions. I've been trying to 'modernise' his article as it has not been updated since 2015 to account for some changes in org but also to take advantage of new packages such as [org-super-agenda](https://github.com/alphapapa/org-super-agenda) and this file is proving very helpful. I wondered have you ever considered creating an org-gtd.el based on this file and perhaps your org-defs.el. Anyway, thanks for your time.

**Comment by Fuco1** [comment]
Hey, thanks for catching that, it's indeed a typo.

Yes, I guess refactor is a good term when talking about code.  In terms of the overall workflow I would call it a "GDT implementation" (I'm not sure if GDT actually has one set way of doing things... it seems to me everyone modifies it a bit).

I've had a note in my todo list to turn this file into a proper package but never got to do it, and it's not really much of a priority for me right now.  Mostly because it is quite personal and it would probably only fit handful of users so it seemed like not the greatest use of my time.  If you want to try something out don't hesitate to copy whatever you need from this.

I have a file lying somewhere which describes my workflow and all the states I use, I'll paste you a link when I find it (I'm at the office right now, it's somewhere on my home computer).

**Comment by Fuco1** [comment]
Well... here's the file copied as a gist (it is in a private repo): https://gist.github.com/Fuco1/4463215033e2943985e16878f5764b85

For habit/goal tracking I have a more elaborate write up here: https://github.com/Fuco1/.emacs.d/blob/master/files/org-defs.org#goals-journaling-and-progress-tracking-with-org-mode
